### ISSUE TITLE
Post release with latest code changes

### ISSUE THREAD

**Issue by DannyMeister** [Nazgul07/ActiveDirectoryPasswordRecycler#2]
There were some code changes since your last release was posted several years ago, which I have been using from building it myself.  Mind posting a release for me to share a download link with non-developers?

**Comment by Nazgul07** [comment]
Sure. I don't remember what I changed but I can do it this weekend. Currently without a computer all week.

**Comment by Nazgul07** [comment]
Well, that took me longer than I'd like to admit. Done now.
